version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    #volumes:
     # - .:/usr/src/app
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_ENV=development
      - App_SETTINGS = src.config.DevelopmentConfig 
      - DATABASE_URL = postgressql://postgres:postgres@api-db:5432/api_dev
      - DATABSE_TEST_URL = postgressql://postgres:postgres@api-db:5432/api_test

    depends_on:
      - api-db
  
  api-db:
    build: 
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres
